apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  target:
    name: rds-secret
  secretStoreRef:
    name: rds-secret-store
    kind: SecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-b2a2e806-cd96-4323-a779-b77198767fac-s9BYyS
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-b2a2e806-cd96-4323-a779-b77198767fac-s9BYyS
        property: password

