apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  target:
    name: rds-secret
  secretStoreRef:
    name: rds-secret-store
    kind: SecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-95bebdc3-a905-4a0b-a4b3-a0b6a3604d98-C7kqL5
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-95bebdc3-a905-4a0b-a4b3-a0b6a3604d98-C7kqL5
        property: password

