apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rds-external-secret
spec:
  refreshPolicy: Periodic
  refreshInterval: 1h
  target:
    name: rds-secret
  secretStoreRef:
    name: rds-secret-store
    kind: SecretStore
  data:
    - secretKey: DB_USER
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-c193f836-ff74-4ff1-a08d-9c591533a877-6a5wrW
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: arn:aws:secretsmanager:ap-northeast-1:619071321369:secret:rds!db-c193f836-ff74-4ff1-a08d-9c591533a877-6a5wrW
        property: password

